### PR TITLE
[firmware] fixes #78 #91 - Coin fractions in Skywallet display

### LINKED ISSUE #78: The hardware wallet shows only up to 2 decimals
**Describe the bug**
When the function for signing transactions is used (added in https://github.com/skycoin/hardware-wallet/pull/62 ), the hardware wallet screen shows the details of the outputs. The problem is that the coins are always shown with 2 decimals, being that this value could have up to 6 decimals.

**Environment information:**

- OS: any
- Platform: any
- Firmware Version: tested with the firmware updated until https://github.com/skycoin/hardware-wallet/commit/e418401d19bc03ce4a366550e479c7bf487632cf

**Steps to Reproduce**
The function can be executed with the JS library and with the cli.

**Actual behavior**
Explained at the beginning.

**Expected behavior**
The hardware wallet should be able to show more decimals. Additionally, it would be good to hide the unnecessary decimals (like showing “1” instead of “1.00”).

### LINKED ISSUE #91: Include path not properly set to run tests on osx
**Describe the bug**
`make test` fails due `gcc` not finding project header files.

**Environment information:**

- OS: Mac OS X
- Platform: `Darwin 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64`
- Firmware Version: git checkout at 720fe1ca

**Steps to Reproduce**

1. Change dir to `skycoin/hardware-wallet` folder
2. Run `make test CFLAGS=-I$(brew --prefix sdl2)/include/SDL2/`

**Actual behavior**

```
$ EMULATOR=1 make -C tiny-firmware/emulator/
cc -I/usr/local/opt/sdl2/include/SDL2/ -MMD -MP -o buttons.o -c buttons.c
buttons.c:20:10: fatal error: 'buttons.h' file not found
#include "buttons.h"
         ^~~~~~~~~~~
1 error generated.
make[2]: *** [buttons.o] Error 1
make[1]: *** [emulator] Error 2
make: *** [test] Error 2
```

**Expected behavior**
At that point emulator of Makefile execution, it should had built the `emulator` and continue with tests for `tiny_firmware`

**Additional context**
Since `sdl2` is installed through `homebrew` , if `CFLAGS` is not provided then this is the output .

```sh

$ EMULATOR=1 make test
make -C skycoin-api/ test
./test_skycoin_crypto
Running suite(s): skycoin_crypto
100%: Checks: 14, Failures: 0, Errors: 0
test_skycoin_crypto.c:73:P:checksums:test_generate_public_key_from_seckey:0: Passed
test_skycoin_crypto.c:86:P:checksums:test_generate_key_pair_from_seed:0: Passed
test_skycoin_crypto.c:105:P:checksums:test_secp256k1Hash:0: Passed
test_skycoin_crypto.c:142:P:checksums:test_generate_deterministic_key_pair_iterator:0: Passed
test_skycoin_crypto.c:161:P:checksums:test_base58_address_from_pubkey:0: Passed
test_skycoin_crypto.c:181:P:checksums:test_bitcoin_address_from_pubkey:0: Passed
test_skycoin_crypto.c:201:P:checksums:test_bitcoin_private_address_from_seckey:0: Passed
test_skycoin_crypto.c:224:P:checksums:test_compute_sha256sum:0: Passed
test_skycoin_crypto.c:268:P:checksums:test_compute_ecdh:0: Passed
test_skycoin_crypto.c:362:P:checksums:test_recover_pubkey_from_signed_message:0: Passed
test_skycoin_crypto.c:57:P:checksums:test_base58_decode:0: Passed
test_skycoin_crypto.c:410:P:checksums:test_signature:0: Passed
test_skycoin_crypto.c:420:P:checksums:test_checkdigest:0: Passed
test_skycoin_crypto.c:826:P:checksums:test_addtransactioninput:0: Passed
PASSED ALL TESTS
make emulator
make -C tiny-firmware/vendor/nanopb/generator/proto/
make[2]: Nothing to be done for `all'.
make -C tiny-firmware/protob/
make[2]: Nothing to be done for `all'.
EMULATOR=1 make -C tiny-firmware/emulator/
cc -DEMULATOR=1 -Wno-pointer-to-int-cast -Wno-int-to-pointer-cast -include stdio.h -include /Users/olemis/Downloads/_/projects/_git/skycoin/hardware-wallet/tiny-firmware/emulator/emulator.h -DHEADLESS=0 -I/usr/include/SDL2 -D_REENTRANT -DCONFIDENTIAL= -O3 -g3 -ggdb3 -std=gnu99 -W -Wall -Wextra -Wimplicit-function-declaration -Wredundant-decls -Wstrict-prototypes -Wundef -Wshadow -Wpointer-arith -Wformat -Wreturn-type -Wsign-compare -Wmultichar -Wformat-nonliteral -Winit-self -Wuninitialized -Wformat-security -Werror -fno-common -fno-exceptions -fvisibility=internal -ffunction-sections -fdata-sections -fstack-protector-all   -DSTM32F2 -DRAND_PLATFORM_INDEPENDENT=1 -I/Users/olemis/Downloads/_/projects/_git/skycoin/hardware-wallet/tiny-firmware/vendor/libopencm3/include -I/Users/olemis/Downloads/_/projects/_git/skycoin/hardware-wallet/tiny-firmware/ -I/Users/olemis/Downloads/_/projects/_git/skycoin/hardware-wallet/tiny-firmware/gen -I/Users/olemis/Downloads/_/projects/_git/skycoin/hardware-wallet/tiny-firmware/vendor/skycoin-crypto -I/Users/olemis/Downloads/_/projects/_git/skycoin/hardware-wallet/tiny-firmware/vendor/skycoin-crypto/tools -I/Users/olemis/Downloads/_/projects/_git/skycoin/hardware-wallet/tiny-firmware/vendor/skycoin-crypto/trezor-tools -I/Users/olemis/Downloads/_/projects/_git/skycoin/hardware-wallet/tiny-firmware/vendor/skycoin-crypto/trezor-tools/aes -DFASTFLASH=0 -DREVERSE_SCREEN=0 -DREVERSE_BUTTONS=0 -DEMULATOR=1 -DDEBUG_RNG=0 -MMD -MP -o buttons.o -c buttons.c
buttons.c:23:10: fatal error: 'SDL.h' file not found
#include <SDL.h>
         ^~~~~~~
1 error generated.
make[2]: *** [buttons.o] Error 1
make[1]: *** [emulator] Error 2
make: *** [test] Error 2
```

### PR DESCRIPTION
**Pull request by olemis**
Fixes #78
Fixes #91 

Changes:
- Change byte size of coins and hours `uint32_t` => `uint64_t`
- Function to render integer coin values as requested in #78 (no conversion to float)
- Include path properly set to run `make test` on osx and linux platforms

Does this change need to mentioned in CHANGELOG.md?
no

Requires testing
yes

Tested with check. Test code refactored to have a `main()` function and a separate mechanism to add test cases .

Related to skycoin/hardware-wallet-js#56 and skycoin/hardware-wallet-go#35

### CODE REVIEW

**Comment by Senyoret1** [comment]
I did some testing and the value looks good on the device screen, so the change that I wanted is working well. However, in the tests I tried with some high values for the coins and the hours and it seems that there is a 32 bit variable that is giving problems when sending a large values. For example, is you send 4294000000 droplets as coins, the device says 4294 coins, but if you send 4295000000 droplets the device says 0.32704 coins, which matches the limit of a 32-bit unsigned variable. Something similar happens with hours.

**Comment by olemis** [comment]
@Senyoret1 the PR changes coin and size values `uitn32_t` => `uint64_t` .

**Comment by olemis** [comment]
> @Senyoret1 the PR changes coin and size values `uitn32_t` => `uint64_t` .

There are companion PR's for similar upgrades in go and js library . In this branch there is a tiny detail pending for resolution . I am working on that now .

**Comment by olemis** [comment]
> > @Senyoret1 the PR changes coin and size values `uitn32_t` => `uint64_t` .
> 
> There are companion PR's for similar upgrades in go and js library . In this branch there is a tiny detail pending for resolution . I am working on that now .

I notice that my reply was not clear enough . Sorry for that . The upgrade to 54 bits in js library is implemented in [`olemis_t51_coins_uint64`](https://github.com/simelo/skycoin-hardware-wallet-js/tree/olemis_t51_coins_uint64) branch .

**Comment by olemis** [comment]
@Senyoret1 requested for your review before merging this

**Pull request merged**
