### PR TITLE
fixes #79 - Support fot large txn

### LINKED ISSUE #79: Allow to create transactions with more than 8 inputs and 8 outputs
**Feature description**
At this time, if the function to create transactions added in https://github.com/skycoin/hardware-wallet/pull/62 is called with more than 8 inputs or 8 outputs, it fails with `Error: array overflow` (at least when being called from the JS library). It would be good if the function allow many more inputs/outputs.

### PR DESCRIPTION
**Pull request by olemis**
Fixes #79

Changes:
- Stream inputs and outputs for transactions with more than 8 inputs and/or 8 outputs

Message sequence :

1. Add an optional completion flag , semantics explained below
1. Completion flag not set for transactions with less than 8 inputs and 8 outputs. This case will be handled exactly same as before applying the changes.
1. Split all inputs into chunks of 8 items max.
1. If the number of inputs is over 8 then messages for all chunks (except the last one) will only contain inputs (i.e. empty outputs). Completion flag set to `false`
1. Split outputs into chunks of 8 items max.
1. The message containing the last inputs chunk is allowed to include the first outputs . Completion flag set to `true` if number of outputs is less than 8 .
1. If the number of outputs is over 8 then messages for other chunks will only contain outputs (i.e. empty inputs). The last chunk with outputs should set completion flag to `true`. Up to this point the wallet will compute inner hash internally
1. Resend (all) inputs (since transactions signed by hardware wallet in full). This is necessary due to the combination of two facts. On the one hand [inputs preceding outputs for inner hash](https://github.com/skycoin/skycoin/blob/develop/src/coin/transactions.go#L470-L476) . On the other hand , properties of crypto hashing functions do not allow for obtaining buffer hash from partial hashing values.

Any mismatch with respect to the above reported back as failure .

Does this change need to mentioned in CHANGELOG.md?
yes

Requires testing
yes

### CODE REVIEW

**Comment by olemis** [comment]
Still WiP

**Comment by therealssj** [comment]
update?

**Comment by jdknives** [comment]
@therealssj similarly, this is a V2 feature and should not have been started. It will remain untouched until the V1 is out.

**Comment by olemis** [comment]
> update?

postponed until v2

**Pull request closed without merging**
