### PR TITLE
Fixes #111 - decimals are not being displayed on transactions

### LINKED ISSUE #111: Decimals are not being displayed when previewing a transaction
**Describe the bug**
When creating a transaction, the device screen only shows the whole part of the amount of coins the user wants to send. For example, if when trying to send 1.5 coins, the screen simply shows 1.

**Environment information:**

- OS: all
- Platform: all
- Firmware Version: develop branch, updated to  4aa0d53.

**Steps to Reproduce**
Create a transaction sending fractions of a coin.

**Actual behavior**
As described at the beginning.

**Expected behavior**
The hardware wallet should show decimals.

**Additional context**
Decimals worked correctly before, so there was probably a problem with some commit added to the develop branch after https://github.com/skycoin/hardware-wallet/pull/93 was merged.

### PR DESCRIPTION
**Pull request by stdevIvr**
Fixes #111 

Changes:
- Fixed the function that converts coins from `uint_64` to `char *` for correctly display decimal digits and check if the number fits into the screen.

Does this change need to mentioned in CHANGELOG.md?
no

Requires testing
yes

### CODE REVIEW

**Comment by stdevStark** [comment]
I added a verification and it fails .

```
Running suite(s): firmware
93%: Checks: 16, Failures: 1, Errors: 0
firmware/test_fsm.c:134:P:fsm:test_msgSkycoinSignMessageReturnIsInHex:0: Passed
firmware/test_fsm.c:62:P:fsm:test_msgGenerateMnemonicImplOk:0: Passed
firmware/test_fsm.c:74:P:fsm:test_msgGenerateMnemonicImplShouldFailIfItWasDone:0: Passed
firmware/test_fsm.c:85:P:fsm:test_msgGenerateMnemonicImplShouldFailForWrongSeedCount:0: Passed
firmware/test_fsm.c:185:P:fsm:test_msgSkycoinCheckMessageSignature:0: Passed
firmware/test_fsm.c:199:P:fsm:test_msgApplySettingsLabelSuccess:0: Passed
firmware/test_fsm.c:219:P:fsm:test_msgFeaturesLabelDefaultsToDeviceId:0: Passed
firmware/test_fsm.c:232:P:fsm:test_msgGetFeatures:0: Passed
firmware/test_fsm.c:211:P:fsm:test_msgApplySettingsLabelSuccessCheck:0: Passed
firmware/test_fsm.c:219:P:fsm:test_msgFeaturesLabelDefaultsToDeviceId:0: Passed
firmware/test_fsm.c:97:P:fsm:test_msgEntropyAckImplFailAsExpectedForSyncProblemInProtocol:0: Passed
firmware/test_fsm.c:117:P:fsm:test_msgGenerateMnemonicEntropyAckSequenceShouldBeOk:0: Passed
firmware/test_droplet.c:23:P:droplet:test_droplet_all_digits:0: Passed
firmware/test_droplet.c:34:P:droplet:test_droplet_small_buffer:0: Passed
firmware/test_droplet.c:42:F:droplet:test_droplet_trim_fraction:0: Assertion '"1.5" == sprint_coins(1500000, 6, 20, msg)' failed: "1.5" == "1.5", sprint_coins(1500000, 6, 20, msg) == "1"
firmware/test_droplet.c:55:P:droplet:test_droplet_trim_integer:0: Passed
```

**Comment by olemis** [comment]
> I added a verification and it fails .

For some weird reason I can not run tests since yesterday . In `make test` linker complaining not finding `_random32` .

**Comment by olemis** [comment]
conflicts and many unrelated commits

**Comment by olemis** [comment]
superseded by #150

**Pull request closed without merging**
