### PR TITLE
AWS deploy ref #210

### LINKED ISSUE #210: Travis should deploy to S3 bucket
**Feature description**

Publish release artifacts onto S3

**Describe the solution you'd like**
Add a new `deploy` entry in `.travis.yml`

**Describe alternatives you've considered**
Since #183 was merged , releases already published on to Github Releases

**Additional context**
Release artifacts are the same ones built in #183 for #50 . Encrypted keys vary from one repository to the other , see 

**Possible implementation**
A similar workflow already implemented in `skycoin/skycoin` .

### PR DESCRIPTION
**Pull request by denisacostaq**
Fixes #210 

Changes:
- Instructions to deploy from Travis to to S3 bucket.

Does this change need to mentioned in CHANGELOG.md?
yes
Requires changes in protobuff specs?
no

Requires testing
no

Comments about testing , should you have some

### CODE REVIEW

**Comment by stdevAlDen** [comment]
@olemis & @gz-c I added the `help` label as I need someone to complete the details in the travis account to make available vars like `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY`, ... in addition it's required to [make the release public](https://github.com/skycoin/hardware-wallet/pull/214/files#diff-354f30a63fb0907d4ad57269548329e3R92) after checking that it's working as expected.

**Comment by stdevAlDen** [comment]
@olemis We need the builds work on windows(aka appveyor)?

**Comment by stdevAlDen** [comment]
> @olemis We need make the builds work on windows(aka appveyor)?

@olemis from the last build I can not see a travis report but an appveyor one(failing), there is any relevant change that I'm not up to date?

**Comment by olemis** [comment]
> in addition it's required to [make the release public](https://github.com/skycoin/hardware-wallet/pull/214/files#diff-354f30a63fb0907d4ad57269548329e3R92) after checking that it's working as expected.

I guess this is a manual step . @gz-c cmiiw

**Pull request merged**
