### PR TITLE
License

### PR DESCRIPTION
**Pull request by mpsido**
Copied the COPYING file from https://github.com/trezor/trezor-mcu/blob/master/COPYING

### CODE REVIEW

**Comment by jdknives** [comment]
@mpsido now we have two copies of LGPL. COPYING is LGPL already. The second license we need is the GPL since  the LGPL requires that we add a GPL copy.

**Comment by jdknives** [comment]
Yes. Thanks.

**Comment by gz-c** [comment]
@jdknives where does it say that we have to relicense a derivative of LGPL-licensed source as GPL?

**Comment by gz-c** [comment]
We also need the author/copyright statements in files added by us, and in files modified by us

**Comment by jdknives** [comment]
> @jdknives where does it say that we have to relicense a derivative of LGPL-licensed source as GPL?

We do not have to relicense it as GPL, but need to include the text of the GPL, since the LGPL makes references to the GPL. For reference check the b) paragraphs of 3 and 4 here: https://opensource.org/licenses/LGPL-3.0 @gz-c

**Comment by jdknives** [comment]
I would suggest we use the Github functionality to show the LGPL v3 on top of the repository so as to make it clearer that we are using LGPL. @gz-c @mpsido  I suggest Mohammed adds the author section, since he should know well which files were modified or added by us. I think we agreed to using the same wording as Trezor, but replace it with Skycoin Project and skycoin.net. Is that correct?

**Comment by gz-c** [comment]
Yes, the file author headers must all be updated

- New files: skycoin
- Modified files: trezor+skycoin
- Unmodified files: trezor

If in the case of a modified file, we have modified a large amount of it, or added significant new functions, move our original code to a new file, to give it a single copyright author (skycoin)

**Comment by mpsido** [comment]
@gz-c  @jdknives  This comment contains two questions/requests.

## 1. I wrote a quick script to detect all the files that I modified on the repo.
However I don't know what it means to write a "trezor+skycoin" license.

```
$for i in $(find -name "*.c" -or -name "*.h"|xargs  grep -l Copyright |grep -v vendor); do echo "Nb commits" $i $(git log $i | grep mpsido |wc -l)  ; done

Nb commits ./bootloader/bootloader.c 5
Nb commits ./bootloader/usb.c 3
Nb commits ./bootloader/signatures.c 1
Nb commits ./memory.c 1
Nb commits ./memory.h 2
Nb commits ./emulator/oled.c 1
Nb commits ./firmware/fsm.c 17
Nb commits ./firmware/fsm.h 3
Nb commits ./firmware/storage.c 2
Nb commits ./firmware/reset.c 2
Nb commits ./firmware/factory_test.h 1
Nb commits ./firmware/factory_test.c 1
Nb commits ./firmware/trezor.c 3
Nb commits ./firmware/layout2.h 1
Nb commits ./firmware/storage.h 1
Nb commits ./firmware/layout2.c 2
Nb commits ./firmware/usb.c 1
```

## 2. Second question

Please check below that the skycoin license file I wrote below is the right one (check the email address and the license).

It that is ok, it is quick and easy for me to write it at the begining of "our files": 

I write it in a file named skycoin-license.txt and then: 

```bash
for i in $(find -name "*.c" -or -name "*.h"|xargs  grep -L Copyright ); do echo Editing $i; cat ../skycoin-license.txt $i > cache; mv cache $i; done
```
```text
/*
 * This file is part of the SKYCOIN project, https://www.skycoin.net/
 *
 * Copyright (C) 2018 <contact@skycoin.net>
 *
 * This library is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this library.  If not, see <http://www.gnu.org/licenses/>.
 */


```

**Comment by gz-c** [comment]
"trezor+skycoin" means to add Skycoin to the author/copyright header alongside trezor

**Comment by olemis** [comment]
> I think @gz-c and Synth did not want the GNU GPL text to be in the repo, but I do think that the LGPL clearly states it needs to be in the repo, even if it is not the governing license for that repo.

what shall be done then ?

**Comment by jdknives** [comment]
@olemis follow Steve's instructions in this case and do not add the GPL text.

**Comment by gz-c** [comment]
Trezor doesn't have a copy of the GPL in the repo. It's fine

**Pull request merged**
